In [238]:
import pandas as pd

In [239]:
file_path = "CCLE_RNAseq_rsem_genes_tpm_20180929.txt.gz"

tpm_df = pd.read_csv(file_path, sep='\t', compression='gzip', index_col=0)

In [285]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lenovo\appdata\roaming\python\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [240]:
tpm_df.head()

,transcript_ids,22RV1_PROSTATE,2313287_STOMACH,253JBV_URINARY_TRACT,253J_URINARY_TRACT,42MGBA_CENTRAL_NERVOUS_SYSTEM,5637_URINARY_TRACT,59M_OVARY,639V_URINARY_TRACT,647V_URINARY_TRACT,...,WSUDLCL2_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,YAPC_PANCREAS,YD10B_UPPER_AERODIGESTIVE_TRACT,YD15_SALIVARY_GLAND,YD38_UPPER_AERODIGESTIVE_TRACT,YD8_UPPER_AERODIGESTIVE_TRACT,YH13_CENTRAL_NERVOUS_SYSTEM,YKG1_CENTRAL_NERVOUS_SYSTEM,ZR751_BREAST,ZR7530_BREAST
gene_id,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.10,"ENST00000373020.4,ENST00000494424.1,ENST000004...",5.28,7.01,22.80,22.88,23.09,57.94,16.30,32.02,60.53,...,0.74,50.29,14.18,24.13,20.94,47.96,28.92,61.08,8.12,16.81
ENSG00000000005.5,"ENST00000373031.4,ENST00000485971.1",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ENSG00000000419.8,"ENST00000371582.4,ENST00000371583.5,ENST000003...",73.38,108.99,56.51,45.39,99.28,98.95,79.68,125.99,89.59,...,41.71,103.70,97.07,104.97,96.86,119.50,64.09,109.13,139.23,56.20
ENSG00000000457.9,"ENST00000367770.1,ENST00000367771.6,ENST000003...",9.76,16.76,2.58,3.25,2.73,3.11,2.69,2.69,2.83,...,5.60,7.76,2.96,5.84,4.17,5.06,4.94,5.91,15.96,13.76
ENSG00000000460.12,"ENST00000286031.6,ENST00000359326.4,ENST000004...",24.51,13.32,10.86,5.26,9.27,31.61,9.62,10.45,15.90,...,20.21,12.84,11.38,14.58,22.13,9.58,13.35,17.40,17.45,11.53

In [241]:
tpm_df = tpm_df.drop(columns=['transcript_ids'])

In [242]:
tpm_df.head()

,22RV1_PROSTATE,2313287_STOMACH,253JBV_URINARY_TRACT,253J_URINARY_TRACT,42MGBA_CENTRAL_NERVOUS_SYSTEM,5637_URINARY_TRACT,59M_OVARY,639V_URINARY_TRACT,647V_URINARY_TRACT,697_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,...,WSUDLCL2_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,YAPC_PANCREAS,YD10B_UPPER_AERODIGESTIVE_TRACT,YD15_SALIVARY_GLAND,YD38_UPPER_AERODIGESTIVE_TRACT,YD8_UPPER_AERODIGESTIVE_TRACT,YH13_CENTRAL_NERVOUS_SYSTEM,YKG1_CENTRAL_NERVOUS_SYSTEM,ZR751_BREAST,ZR7530_BREAST
gene_id,,,,,,,,,,,,,,,,,,,,,
ENSG00000000003.10,5.28,7.01,22.80,22.88,23.09,57.94,16.30,32.02,60.53,0.11,...,0.74,50.29,14.18,24.13,20.94,47.96,28.92,61.08,8.12,16.81
ENSG00000000005.5,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ENSG00000000419.8,73.38,108.99,56.51,45.39,99.28,98.95,79.68,125.99,89.59,43.03,...,41.71,103.70,97.07,104.97,96.86,119.50,64.09,109.13,139.23,56.20
ENSG00000000457.9,9.76,16.76,2.58,3.25,2.73,3.11,2.69,2.69,2.83,4.19,...,5.60,7.76,2.96,5.84,4.17,5.06,4.94,5.91,15.96,13.76
ENSG00000000460.12,24.51,13.32,10.86,5.26,9.27,31.61,9.62,10.45,15.90,19.54,...,20.21,12.84,11.38,14.58,22.13,9.58,13.35,17.40,17.45,11.53

In [243]:
tpm_df_T = tpm_df.T
tpm_df_T.index.name = 'mapped_key'
tpm_df_T = tpm_df_T.reset_index()

In [244]:
tpm_df_T.head()

gene_id,mapped_key,ENSG00000000003.10,ENSG00000000005.5,ENSG00000000419.8,ENSG00000000457.9,ENSG00000000460.12,ENSG00000000938.8,ENSG00000000971.11,ENSG00000001036.9,ENSG00000001084.6,...,ENSGR0000237531.1,ENSGR0000237801.1,ENSGR0000263835.1,ENSGR0000263980.1,ENSGR0000264510.1,ENSGR0000264819.1,ENSGR0000265350.1,ENSGR0000265658.1,ENSGR0000266731.1,ENSGR0000270726.1
0,22RV1_PROSTATE,5.28,0.0,73.38,9.76,24.51,0.01,0.08,54.86,118.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2313287_STOMACH,7.01,0.0,108.99,16.76,13.32,0.00,0.23,170.91,93.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,253JBV_URINARY_TRACT,22.80,0.0,56.51,2.58,10.86,0.00,0.06,30.78,22.16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,253J_URINARY_TRACT,22.88,0.0,45.39,3.25,5.26,0.00,0.28,45.05,19.45,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,42MGBA_CENTRAL_NERVOUS_SYSTEM,23.09,0.0,99.28,2.73,9.27,0.02,0.45,53.29,8.36,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [245]:
tpm_df_T.shape

(1019, 57821)

In [246]:
metadata_df=pd.read_csv("Model.csv")

In [247]:
metadata_df.head()

,ModelID,PatientID,CellLineName,StrippedCellLineName,Age,SourceType,SangerModelID,RRID,DepmapModelType,AgeCategory,...,PublicComments,WTSIMasterCellID,EngineeredModel,TreatmentStatus,OnboardedMedia,PlateCoating,OncotreeCode,OncotreeSubtype,OncotreePrimaryDisease,OncotreeLineage
0,ACH-000001,PT-gj46wT,NIH:OVCAR-3,NIHOVCAR3,60.0,Commercial,SIDM00105,CVCL_0465,HGSOC,Adult,...,NaN,2201.0,NaN,NaN,MF-001-041,NaN,HGSOC,High-Grade Serous Ovarian Cancer,Ovarian Epithelial Tumor,Ovary/Fallopian Tube
1,ACH-000002,PT-5qa3uk,HL-60,HL60,36.0,Commercial,SIDM00829,CVCL_0002,AML,Adult,...,NaN,55.0,NaN,NaN,MF-005-001,NaN,AML,Acute Myeloid Leukemia,Acute Myeloid Leukemia,Myeloid
2,ACH-000003,PT-puKIyc,CACO2,CACO2,72.0,Commercial,SIDM00891,CVCL_0025,COAD,Adult,...,NaN,NaN,NaN,Unknown,MF-015-009,NaN,COAD,Colon Adenocarcinoma,Colorectal Adenocarcinoma,Bowel
3,ACH-000004,PT-q4K2cp,HEL,HEL,30.0,Commercial,SIDM00594,CVCL_0001,AML,Adult,...,NaN,783.0,NaN,Post-treatment,MF-001-001,NaN,AML,Acute Myeloid Leukemia,Acute Myeloid Leukemia,Myeloid
4,ACH-000005,PT-q4K2cp,HEL 92.1.7,HEL9217,30.0,Commercial,SIDM00593,CVCL_2481,AML,Adult,...,NaN,NaN,NaN,NaN,MF-001-001,NaN,AML,Acute Myeloid Leukemia,Acute Myeloid Leukemia,Myeloid

In [248]:

gene_expr_cols = RNAseq_rsem_genes.columns.tolist()

mapping = {}
for col in gene_expr_cols:
    matched_rows = metadata_df[metadata_df['CCLEName'] == col]
    if not matched_rows.empty:
        mapping[col] = matched_rows.iloc[0]['CellLineName']  
    else:
        mapping[col] = None

In [249]:
drugcomb=pd.read_csv("drug_interaction_drugcomb.csv",low_memory=False)

In [250]:
drugcomb.head()

,block_id,drug_row,drug_col,cell_line_name,conc_r_unit,conc_c_unit,css,synergy_zip,synergy_bliss,synergy_loewe,synergy_hsa,ic50_row,ic50_col,ri_row,ri_col,css_row,css_col,S
0,1,5-FU,ABT-888,A2058,uM,uM,30.869,3.865915,6.256584,-2.951386,5.536903,5.126836,3.267734,11.471,-0.441,22.545,39.193,19.839
1,2,5-FU,ABT-888,A2058,uM,uM,27.460,8.247403,12.333896,3.125927,11.614215,5.126836,3.267734,11.471,-0.441,24.135,30.785,16.430
2,3,5-FU,ABT-888,A2058,uM,uM,29.901,6.063440,11.660209,2.452239,10.940528,5.126836,3.267734,11.471,-0.441,25.561,34.241,18.871
3,4,5-FU,ABT-888,A2058,uM,uM,24.016,-4.280231,5.145209,-4.062761,4.425528,5.126836,3.267734,11.471,-0.441,16.661,31.371,12.986
4,5,5-FU,AZD1775,A2058,uM,uM,66.847,12.284698,15.765467,10.409407,18.656340,5.126836,0.266027,11.471,25.164,76.501,57.193,30.212

In [251]:
unique_cell_lines = drugcomb['cell_line_name'].drop_duplicates().reset_index(drop=True)

unique_cell_lines_df = pd.DataFrame(unique_cell_lines, columns=['cell_line_name'])

unique_cell_lines.head()

0    A2058
1    A2780
2     A375
3     A427
4    CAOV3
Name: cell_line_name, dtype: object

In [252]:
reverse_mapping = {v: k for k, v in mapping.items() if v is not None}
unique_cell_lines_df['mapped_key'] = unique_cell_lines_df['cell_line_name'].map(reverse_mapping)

In [253]:
unique_cell_lines_df

            cell_line_name            mapped_key
0                    A2058            A2058_SKIN
1                    A2780           A2780_OVARY
2                     A375                   NaN
3                     A427             A427_LUNG
4                    CAOV3                   NaN
...                    ...                   ...
1349               SNU-869  SNU869_BILIARY_TRACT
1350               UM-UC-1   UMUC1_URINARY_TRACT
1351  CJM [Human melanoma]                   NaN
1352                HuG1-N         HUG1N_STOMACH
1353                  LMSU          LMSU_STOMACH

[1354 rows x 2 columns]

In [254]:
final_gene_expression = unique_cell_lines_df.merge(tpm_df_T, on='mapped_key', how='left')

In [255]:
final_gene_expression.drop(columns='mapped_key',inplace=True)

In [256]:
final_gene_expression.dropna(inplace=True)

In [257]:
final_gene_expression.shape

(717, 57821)

In [258]:
final_gene_expression.to_csv("final_cellline_geneexpression.csv")

In [259]:
file_path = "gencode.v48.annotation.gff3.gz"

columns = [
    "seqid", "source", "type", "start", "end",
    "score", "strand", "phase", "attributes"
]

gene_df = pd.read_csv(
    file_path,
    sep="\t",
    compression="gzip",
    comment="#",
    names=columns,
    dtype=str
)

In [260]:
gene_df.head()

,seqid,source,type,start,end,score,strand,phase,attributes
0,chr1,HAVANA,gene,11121,24894,.,+,.,ID=ENSG00000290825.2;gene_id=ENSG00000290825.2...
1,chr1,HAVANA,transcript,11121,14413,.,+,.,ID=ENST00000832824.1;Parent=ENSG00000290825.2;...
2,chr1,HAVANA,exon,11121,11211,.,+,.,ID=exon:ENST00000832824.1:1;Parent=ENST0000083...
3,chr1,HAVANA,exon,12010,12227,.,+,.,ID=exon:ENST00000832824.1:2;Parent=ENST0000083...
4,chr1,HAVANA,exon,12613,12721,.,+,.,ID=exon:ENST00000832824.1:3;Parent=ENST0000083...

In [261]:
file_path = "gencode.v48.chr_patch_hapl_scaff.basic.annotation.gff3.gz"

columns = [
    "seqid", "source", "type", "start", "end",
    "score", "strand", "phase", "attributes"
]

gene_df = pd.read_csv(
    file_path,
    sep="\t",
    compression="gzip",
    comment="#",
    names=columns,
    dtype=str
)

In [262]:
gene_df.head()

,seqid,source,type,start,end,score,strand,phase,attributes
0,chr1,HAVANA,gene,11121,24894,.,+,.,ID=ENSG00000290825.2;gene_id=ENSG00000290825.2...
1,chr1,HAVANA,transcript,11426,14409,.,+,.,ID=ENST00000832828.1;Parent=ENSG00000290825.2;...
2,chr1,HAVANA,exon,11426,11671,.,+,.,ID=exon:ENST00000832828.1:1;Parent=ENST0000083...
3,chr1,HAVANA,exon,12010,12227,.,+,.,ID=exon:ENST00000832828.1:2;Parent=ENST0000083...
4,chr1,HAVANA,exon,12613,12721,.,+,.,ID=exon:ENST00000832828.1:3;Parent=ENST0000083...

In [263]:
annotation_df = gene_df.copy()

In [264]:
genes_df = annotation_df[annotation_df['type'] == 'gene']

In [265]:
genes_df.attributes

0          ID=ENSG00000290825.2;gene_id=ENSG00000290825.2...
6          ID=ENSG00000223972.6;gene_id=ENSG00000223972.6...
14         ID=ENSG00000310526.1;gene_id=ENSG00000310526.1...
108        ID=ENSG00000227232.6;gene_id=ENSG00000227232.6...
120        ID=ENSG00000278267.1;gene_id=ENSG00000278267.1...
                                 ...
2424339    ID=ENSG00000303867.1;gene_id=ENSG00000303867.1...
2424411    ID=ENSG00000303902.1;gene_id=ENSG00000303902.1...
2424434    ID=ENSG00000306528.1;gene_id=ENSG00000306528.1...
2424439    ID=ENSG00000297844.1;gene_id=ENSG00000297844.1...
2424443    ID=ENSG00000309258.1;gene_id=ENSG00000309258.1...
Name: attributes, Length: 86364, dtype: object

In [266]:
def parse_attributes(attr_str):
    attrs = {}
    for attr in attr_str.split(';'):
        if '=' in attr:
            key, value = attr.strip().split('=', 1)
            attrs[key] = value
    return attrs

In [267]:
genes_df['attrs_dict'] = genes_df['attributes'].apply(parse_attributes)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9520\4057569586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genes_df['attrs_dict'] = genes_df['attributes'].apply(parse_attributes)

In [268]:
genes_df

,seqid,source,type,start,end,score,strand,phase,attributes,attrs_dict
0,chr1,HAVANA,gene,11121,24894,.,+,.,ID=ENSG00000290825.2;gene_id=ENSG00000290825.2...,"{'ID': 'ENSG00000290825.2', 'gene_id': 'ENSG00..."
6,chr1,HAVANA,gene,12010,13670,.,+,.,ID=ENSG00000223972.6;gene_id=ENSG00000223972.6...,"{'ID': 'ENSG00000223972.6', 'gene_id': 'ENSG00..."
14,chr1,HAVANA,gene,14356,30744,.,-,.,ID=ENSG00000310526.1;gene_id=ENSG00000310526.1...,"{'ID': 'ENSG00000310526.1', 'gene_id': 'ENSG00..."
108,chr1,HAVANA,gene,14696,24886,.,-,.,ID=ENSG00000227232.6;gene_id=ENSG00000227232.6...,"{'ID': 'ENSG00000227232.6', 'gene_id': 'ENSG00..."
120,chr1,ENSEMBL,gene,17369,17436,.,-,.,ID=ENSG00000278267.1;gene_id=ENSG00000278267.1...,"{'ID': 'ENSG00000278267.1', 'gene_id': 'ENSG00..."
...,...,...,...,...,...,...,...,...,...,...
2424339,KI270751.1,HAVANA,gene,2579,73732,.,-,.,ID=ENSG00000303867.1;gene_id=ENSG00000303867.1...,"{'ID': 'ENSG00000303867.1', 'gene_id': 'ENSG00..."
2424411,KI270751.1,HAVANA,gene,34096,71851,.,+,.,ID=ENSG00000303902.1;gene_id=ENSG00000303902.1...,"{'ID': 'ENSG00000303902.1', 'gene_id': 'ENSG00..."
2424434,KI270751.1,HAVANA,gene,133801,139253,.,-,.,ID=ENSG00000306528.1;gene_id=ENSG00000306528.1...,"{'ID': 'ENSG00000306528.1', 'gene_id': 'ENSG00..."
2424439,KI270753.1,HAVANA,gene,43135,44491,.,+,.,ID=ENSG00000297844.1;gene_id=ENSG00000297844.1...,"{'ID': 'ENSG00000297844.1', 'gene_id': 'ENSG00..."
2424443,KI270755.1,HAVANA,gene,26350,27723,.,+,.,ID=ENSG00000309258.1;gene_id=ENSG00000309258.1...,"{'ID': 'ENSG00000309258.1', 'gene_id': 'ENSG00..."

In [269]:
genes_df['gene_id'] = genes_df['attrs_dict'].apply(lambda x: x.get('gene_id'))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9520\31059747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genes_df['gene_id'] = genes_df['attrs_dict'].apply(lambda x: x.get('gene_id'))

In [270]:
genes_df['gene_type'] = genes_df['attrs_dict'].apply(lambda x: x.get('gene_type'))

C:\Users\lenovo\AppData\Local\Temp\ipykernel_9520\4002199453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genes_df['gene_type'] = genes_df['attrs_dict'].apply(lambda x: x.get('gene_type'))

In [271]:
protein_coding_genes = genes_df[genes_df['gene_type'] == 'protein_coding']['gene_id'].tolist()

In [272]:
len(protein_coding_genes)

23262

In [273]:
protein_coding_genes_no_version = [gene.split('.')[0] for gene in protein_coding_genes]

In [274]:
expr_genes_no_version = final_gene_expression.columns.str.split('.').str[0]

In [275]:
expr_genes_no_version

Index(['cell_line_name', 'ENSG00000000003', 'ENSG00000000005',
       'ENSG00000000419', 'ENSG00000000457', 'ENSG00000000460',
       'ENSG00000000938', 'ENSG00000000971', 'ENSG00000001036',
       'ENSG00000001084',
       ...
       'ENSGR0000237531', 'ENSGR0000237801', 'ENSGR0000263835',
       'ENSGR0000263980', 'ENSGR0000264510', 'ENSGR0000264819',
       'ENSGR0000265350', 'ENSGR0000265658', 'ENSGR0000266731',
       'ENSGR0000270726'],
      dtype='object', length=57821)

In [276]:
mask = expr_genes_no_version.isin(protein_coding_genes_no_version)

In [277]:
final_gene_expression.head()

,cell_line_name,ENSG00000000003.10,ENSG00000000005.5,ENSG00000000419.8,ENSG00000000457.9,ENSG00000000460.12,ENSG00000000938.8,ENSG00000000971.11,ENSG00000001036.9,ENSG00000001084.6,...,ENSGR0000237531.1,ENSGR0000237801.1,ENSGR0000263835.1,ENSGR0000263980.1,ENSGR0000264510.1,ENSGR0000264819.1,ENSGR0000265350.1,ENSGR0000265658.1,ENSGR0000266731.1,ENSGR0000270726.1
0,A2058,15.67,0.00,97.03,5.11,23.03,0.02,7.43,94.70,14.35,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A2780,94.32,2.53,119.23,5.92,21.57,0.03,248.72,19.78,12.86,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A427,19.18,0.00,95.22,2.73,11.14,0.01,0.13,45.33,10.43,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,NCI-H460,23.21,0.00,82.35,2.74,19.65,0.02,12.89,43.91,65.63,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,RKO,11.89,0.02,153.59,1.43,12.71,0.00,0.13,56.71,15.72,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [278]:
filtered_expr_df = final_gene_expression.loc[:, mask]

In [279]:
filtered_expr_df.head()

,ENSG00000000003.10,ENSG00000000005.5,ENSG00000000419.8,ENSG00000000457.9,ENSG00000000460.12,ENSG00000000938.8,ENSG00000000971.11,ENSG00000001036.9,ENSG00000001084.6,ENSG00000001167.10,...,ENSG00000273238.1,ENSG00000273259.1,ENSG00000273269.1,ENSG00000273274.1,ENSG00000273291.1,ENSG00000273294.1,ENSG00000273313.1,ENSG00000273331.1,ENSG00000273345.1,ENSG00000273398.1
0,15.67,0.00,97.03,5.11,23.03,0.02,7.43,94.70,14.35,23.58,...,0.00,0.28,0.0,0.08,0.0,0.87,0.00,0.00,0.18,0.06
1,94.32,2.53,119.23,5.92,21.57,0.03,248.72,19.78,12.86,22.23,...,0.06,0.00,0.0,0.13,0.0,0.00,0.02,0.00,0.22,0.03
3,19.18,0.00,95.22,2.73,11.14,0.01,0.13,45.33,10.43,21.23,...,0.00,0.00,0.0,0.16,0.0,0.13,0.04,0.02,0.06,0.05
20,23.21,0.00,82.35,2.74,19.65,0.02,12.89,43.91,65.63,12.35,...,0.00,0.00,0.0,0.00,0.0,0.06,0.23,0.23,0.06,0.07
26,11.89,0.02,153.59,1.43,12.71,0.00,0.13,56.71,15.72,21.12,...,0.00,0.00,0.0,0.00,0.0,0.00,6.03,0.49,0.49,0.00

In [280]:
filtered_expr_df.isnull().sum().sum()

np.int64(0)

In [281]:
filtered_expr_df.shape

(717, 19225)

In [282]:
filtered_expr_df = filtered_expr_df.copy()  # avoid SettingWithCopyWarning
filtered_expr_df.insert(0, 'cell_line_name', final_gene_expression['cell_line_name'])

In [283]:
filtered_expr_df.head()

,cell_line_name,ENSG00000000003.10,ENSG00000000005.5,ENSG00000000419.8,ENSG00000000457.9,ENSG00000000460.12,ENSG00000000938.8,ENSG00000000971.11,ENSG00000001036.9,ENSG00000001084.6,...,ENSG00000273238.1,ENSG00000273259.1,ENSG00000273269.1,ENSG00000273274.1,ENSG00000273291.1,ENSG00000273294.1,ENSG00000273313.1,ENSG00000273331.1,ENSG00000273345.1,ENSG00000273398.1
0,A2058,15.67,0.00,97.03,5.11,23.03,0.02,7.43,94.70,14.35,...,0.00,0.28,0.0,0.08,0.0,0.87,0.00,0.00,0.18,0.06
1,A2780,94.32,2.53,119.23,5.92,21.57,0.03,248.72,19.78,12.86,...,0.06,0.00,0.0,0.13,0.0,0.00,0.02,0.00,0.22,0.03
3,A427,19.18,0.00,95.22,2.73,11.14,0.01,0.13,45.33,10.43,...,0.00,0.00,0.0,0.16,0.0,0.13,0.04,0.02,0.06,0.05
20,NCI-H460,23.21,0.00,82.35,2.74,19.65,0.02,12.89,43.91,65.63,...,0.00,0.00,0.0,0.00,0.0,0.06,0.23,0.23,0.06,0.07
26,RKO,11.89,0.02,153.59,1.43,12.71,0.00,0.13,56.71,15.72,...,0.00,0.00,0.0,0.00,0.0,0.00,6.03,0.49,0.49,0.00

In [284]:
filtered_expr_df.to_csv("finalP_cell_line_feature.csv")